version: '3.7'

services:
  mysql:
    container_name: admin-cursos_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_cursos
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - adm_cursos_network

networks:
  adm_cursos_network: